import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import ConvexClientProvider from "@/components/providers/ConvexClientProvider";
import Footer from "@/components/Footer";
import type { Viewport } from 'next';
import { Toaster } from "react-hot-toast";
import WelcomeToastOnSignIn from "./_components/WelcomeToastOnSignIn";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
  display: "swap", // Optimized font loading
  preload: true,
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
  display: "swap",
  preload: true,
});



export const metadata: Metadata = {
  title: "Code Craft and Sync",
  description: "Generated by create next app",
  icons: {
    icon: "/1.ico",
  },
}


export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
  userScalable: true,
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#ffffff' },
    { media: '(prefers-color-scheme: dark)', color: '#0a0a0a' },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="scroll-smooth">
        <head>
          {/* Preload critical resources */}
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
          <link rel="dns-prefetch" href="https://api.clerk.com" />
        </head>
        <body
          className={`
            ${geistSans.variable} ${geistMono.variable} antialiased
            flex flex-col min-h-screen
            bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900
            text-gray-100
            selection:bg-purple-500/30 selection:text-purple-100
            transition-colors duration-300 ease-in-out
            overflow-x-hidden
            relative
          `}
        >
          <Toaster position="top-right" />
          <WelcomeToastOnSignIn />
          {/* Enhanced animated background with better performance */}
          <div className="fixed inset-0 overflow-hidden pointer-events-none">
            {/* Primary gradient overlay */}
            <div className="absolute inset-0 bg-gradient-to-br from-purple-900/20 via-blue-900/10 to-indigo-900/20"></div>
            
            {/* Animated orbs with optimized animations */}
            <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-purple-500/5 rounded-full blur-3xl animate-pulse-slow"></div>
            <div className="absolute top-3/4 right-1/4 w-80 h-80 bg-blue-500/5 rounded-full blur-3xl animate-pulse-slow" style={{animationDelay: '2s'}}></div>
            <div className="absolute top-1/2 left-3/4 w-72 h-72 bg-indigo-500/5 rounded-full blur-3xl animate-pulse-slow" style={{animationDelay: '4s'}}></div>
            
            {/* Moving particles for depth */}
            <div className="absolute inset-0">
              <div className="absolute top-1/3 left-1/3 w-2 h-2 bg-purple-400/20 rounded-full animate-float"></div>
              <div className="absolute top-2/3 right-1/3 w-1 h-1 bg-blue-400/20 rounded-full animate-float" style={{animationDelay: '1s'}}></div>
              <div className="absolute top-1/2 left-2/3 w-1.5 h-1.5 bg-indigo-400/20 rounded-full animate-float" style={{animationDelay: '3s'}}></div>
            </div>
          </div>

          {/* Glassmorphism overlay */}
          <div className="fixed inset-0 bg-gradient-to-br from-white/[0.03] via-transparent to-black/[0.05] pointer-events-none backdrop-blur-[0.5px]"></div>

          {/* Main content with improved layout */}
          <ConvexClientProvider>
            <main className="
              flex-1 w-full max-w-8xl mx-auto
              px-3 sm:px-4 md:px-6 lg:px-8 xl:px-10 2xl:px-12
              py-4 sm:py-6 md:py-8 lg:py-10 xl:py-12
              relative z-10
              min-h-screen
              flex flex-col
            ">
              {/* Content wrapper with subtle border */}
              <div className="
                flex-1 w-full
                rounded-xl
                border border-white/5
                bg-gradient-to-br from-white/[0.02] to-transparent
                backdrop-blur-sm
                p-1
                shadow-2xl shadow-purple-900/20
              ">
                <div className="w-full h-full rounded-lg overflow-hidden">
                  {children}
                </div>
              </div>
            </main>

            {/* Enhanced footer with glassmorphism */}
            <div className="relative z-10 border-t border-white/5 bg-black/20 backdrop-blur-sm">
              <Footer />
            </div>
          </ConvexClientProvider>

          {/* Optimized noise texture */}
          <div 
            className="fixed inset-0 opacity-[0.015] pointer-events-none mix-blend-overlay"
            style={{
              backgroundImage: `url("data:image/svg+xml,%3Csvg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noiseFilter'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='1' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noiseFilter)'/%3E%3C/svg%3E")`,
              backgroundSize: '200px 200px'
            }}
          ></div>

          {/* Loading indicator for better UX */}
          <div id="loading-indicator" className="fixed top-0 left-0 w-full h-1 bg-gradient-to-r from-purple-500 to-blue-500 z-50 opacity-0 transition-opacity duration-300"></div>
        </body>
      </html>
    </ClerkProvider>
  );
}